api_version: 1
project_config:
  project_name: mytv_feathr

spark_config:
  # choice for spark runtime. Currently, support: azure_synapse, databricks, local
  spark_cluster: 'local'
  spark_result_output_parts: '1'
  local:
    master: 'local[*]'
    feathr_runtime_location: "./vnpt_feathr-0.0.1.jar"


online_store:
  redis:
    # Redis configs to access Redis cluster
    host: '127.0.0.1'
    port: 6379
    ssl_enabled: False

feature_registry:
  # The API endpoint of the registry service
  api_endpoint: "http://127.0.0.1:8081/api/v1"
